base_path: "/glade/work/rjarolim/sunerf/aia_v02"
work_directory: "/glade/derecho/scratch/rjarolim/sunerf/aia_v02"

data:
  data_config:
    - type: 'AIA'
      data_path: '/glade/work/rjarolim/data/sunerf/2012_08_prep/aia/*.fits'
  debug: False
  batch_size: 2048
  num_workers: 16

logging:
  project: "sunerf"
  name: "AIA"

training:
  log_every_n_steps: 2000

model:
  model_config:
    dim: 128
    activation: 'swish'
  image_scaling_config:
    AIA: { vmax: 1.0 }
  temperature_response_config:
    AIA: { model: '/glade/work/rjarolim/sunerf/response/aia.pt', scaling: 0.0, n_channels: 7, learnable: False }