base_path: "/glade/work/rjarolim/sunerf/psi_v03"
work_directory: "/glade/derecho/scratch/rjarolim/sunerf/psi_v03"

data:
  data_config:
    - type: 'PSI'
      data_path: '/glade/work/rjarolim/data/sunerf/psi_data_prep/'
      wavelengths: [171, 193, 211]
      scaling: 50000.0
  batch_size: 1024
  num_workers: 16

logging:
  project: "sunerf"
  name: "PSI"

training:
  log_every_n_steps: 1000

model:
  model_config:
    encoding: positional
    dim: 128
  image_scaling_config:
    PSI: { vmax: 1.0 }
  temperature_response_config:
    PSI: { model: '/glade/work/rjarolim/sunerf/response/psi_mean.pt', scaling: 0.0, n_channels: 1, learnable: False }